import discord
from discord.ext import commands
import aiohttp
import asyncio
import os
import zipfile
import tempfile
from pathlib import Path

# Bot configuration
TOKEN = "MTQ3NjYwNTAxMDUwMTQzOTU0OA.G3LaxK.fZlnILy97sdYpcPdHM3iMilnt_htym2axHyeT8"  # Replace with your bot token
PREFIX = "!"

# Initialize bot
intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix=PREFIX, intents=intents)

# Mock manifest data for demonstration
MANIFEST_TEMPLATE = """// Manifest file for AppID {appid}
"AppState"
{{
    "appid"         "{appid}"
    "Universe"      "1"
    "name"          "{game_name}"
    "StateFlags"    "4"
    "installdir"    "{game_name}"
    "LastUpdated"   "0"
    "UpdateResult"  "0"
    "SizeOnDisk"    "0"
    "buildid"       "0"
    "LastOwner"     "0"
    "BytesToDownload" "0"
    "BytesDownloaded" "0"
    "AutoUpdateBehavior" "0"
    "AllowOtherRunningWhileRunning" "false"
    "Shared depot downloads" "0"
    "Configuration manifest" ""
}}"""

# Common game names for demonstration
COMMON_GAMES = {
    "730": "Counter-Strike: Global Offensive",
    "570": "Dota 2",
    "440": "Team Fortress 2",
    "230410": "Rocket League",
    "252950": "The Witcher 3: Wild Hunt",
    "377160": "The Binding of Isaac: Rebirth",
    "220200": "The Elder Scrolls V: Skyrim Special Edition",
    "108600": "The Binding of Isaac: Afterbirth+",
    "221380": "Stardew Valley",
    "220240": "Warframe",
    "105600": "Terraria",
    "221100": "The Forest",
    "250900": "The Long Dark",
    "220500": "The Sims 4",
    "289070": "The Witness",
    "381210": "Dead Cells",
    "413150": "Stellaris",
    "583950": "Divinity: Original Sin 2",
    "620980": "Celeste",
    "268910": "TORN"
}

@bot.event
async def on_ready():
    print(f'{bot.user} has connected to Discord!')
    print(f'Bot is in {len(bot.guilds)} guilds')
    print("⚠️  NOTE: This bot creates demonstration manifest files only.")
    print("    For real Steam manifests, you would need steamtools or access to Ryuu's API.")

@bot.command(name='gen')
async def generate_manifest(ctx, appid: str):
    """
    Generate a demonstration manifest for given AppID
    Usage: !gen <appid>
    """
    # Validate appid is numeric
    if not appid.isdigit():
        await ctx.send("❌ Please provide a valid numeric AppID")
        return
    
    await ctx.send(f"🔄 Creating demonstration manifest for AppID {appid}...")
    
    try:
        # Get game name (use common name if available, otherwise generic)
        game_name = COMMON_GAMES.get(appid, f"Game_{appid}")
        
        # Create temporary directory for our work
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            manifest_dir = temp_path / "manifest"
            manifest_dir.mkdir()
            
            # Create manifest file
            manifest_content = MANIFEST_TEMPLATE.format(appid=appid, game_name=game_name)
            manifest_file = manifest_dir / f"appmanifest_{appid}.acf"
            
            with open(manifest_file, 'w') as f:
                f.write(manifest_content)
            
            # Create info file
            info_file = manifest_dir / "info.txt"
            with open(info_file, 'w') as f:
                f.write(f"""Steam Manifest Demonstration
AppID: {appid}
Game: {game_name}
Generated by: OpenClaw Manifest Bot
Note: This is a demonstration file. Real Steam manifests require steamtools or official Steam access.
""")
            
            # Create zip file
            zip_path = temp_path / f"manifest_{appid}.zip"
            with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
                for file_path in manifest_dir.iterdir():
                    if file_path.is_file():
                        zipf.write(file_path, file_path.name)
            
            # Check if zip is too large for Discord (limit is ~25MB)
            if zip_path.stat().st_size > 25 * 1024 * 1024:
                await ctx.send(f"❌ Manifest zip is too large (>25MB) to send via Discord.")
                return
            
            # Send the zip file
            await ctx.send(
                f"📦 Here's the demonstration manifest for AppID {appid} ({game_name}):\n"
                f"⚠️  **Note**: This is a demonstration file. For real Steam manifests, you would need steamtools or official Steam access.",
                file=discord.File(zip_path)
            )
            
    except Exception as e:
        await ctx.send(f"❌ An error occurred: {str(e)}")
        print(f"Error in !gen command: {e}")

@bot.command(name='helpmanifest')
async def help_manifest(ctx):
    """Show help for manifest commands"""
    embed = discord.Embed(
        title="📋 Manifest Bot Help (Demonstration Mode)",
        description="Commands for generating demonstration Steam manifest files\nNote: This bot creates demo files only - not real Steam manifests",
        color=discord.Color.orange()
    )
    embed.add_field(
        name="!gen <appid>",
        value="Generate demonstration manifest zip for the given Steam AppID\nExample: `!gen 730` for CS:GO\nCreates a demonstration file only",
        inline=False
    )
    embed.add_field(
        name="!helpmanifest",
        value="Show this help message",
        inline=False
    )
    embed.add_field(
        name="!examples",
        value="Show example AppIDs for popular games",
        inline=False
    )
    await ctx.send(embed=embed)

@bot.command(name='examples')
async def show_examples(ctx):
    """Show example AppIDs"""
    embed = discord.Embed(
        title="🎮 Example AppIDs",
        description="Popular game AppIDs you can use with !gen command",
        color=discord.Color.blue()
    )
    
    examples_text = ""
    for appid, name in list(COMMON_GAMES.items())[:10]:
        examples_text += f"`{appid}` - {name}\n"
    
    embed.add_field(
        name="Popular Games",
        value=examples_text or "None",
        inline=False
    )
    
    embed.add_field(
        name="Note",
        value="This bot creates demonstration manifest files only.\nFor real Steam manifests, you would need steamtools or official Steam access.",
        inline=False
    )
    
    await ctx.send(embed=embed)

# Run the bot
if __name__ == "__main__":
    # You'll need to set your Discord bot token as an environment variable
    # or replace TOKEN above with your actual bot token
    token = os.getenv('DISCORD_BOT_TOKEN', TOKEN)
    if token == "YOUR_DISCORD_BOT_TOKEN_HERE":
        print("⚠️  WARNING: Please set your Discord bot token!")
        print("You can:")
        print("1. Replace TOKEN in the code with your bot token")
        print("2. Set environment variable DISCORD_BOT_TOKEN")
        print("3. Get a token from https://discord.com/developers/applications")
    else:
        bot.run(token)
