[phases.setup]
nixPkgs = [
    "python313", 
    "chromium",
    "google-chrome",
    "glib",
    "nss",
    "nspr",
    "atk",
    "at-spi2-atk",
    "libdrm",
    "mesa",
    "gbm",
    "pango",
    "cairo",
    "alsa-lib"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python bot.py"
